### ISSUE TITLE
error importing badge

### ISSUE THREAD

**Issue by sleslie** [concentricsky/badgr-server#5] opened 2015-06-24 17:25 UTC
Tried to upload an image I _thought_ was a badge at https://badgr.io/earner. Got the following unescaped error message 

    html 500 Error submitting form: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <title>Badgr</title> <link rel="shortcut icon" href="images/favicon.ico" /> <meta name="viewport" content="width=device-width,initial-scale=1"> <link rel="stylesheet" media="screen" type="text/css" href="css/bootstrap/css/bootstrap.css">   <link href="css/plugins/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">  <link rel="stylesheet" media="screen" type="text/css" href="css/style.css">  <script src="js/libs/modernizr-2.5.3.min.js"></script> </head> <body class="badgr "> <p class="error500">We're sorry, an error has occurred.</p> <footer class="main-footer clearfix wrap page-wrapper"> <div class="container-fluid"> <div class="row"> <div class="col-xs-6 col-sm-4"> <span class="vendor-info"> Powered by <a href="https://github.com/concentricsky/badgr-server">Badgr</a> </span> </div> <div class="col-xs-6 col-sm-8"> <ul class="footer-links">  <li><a href="/docs">API documentation</a></li> </ul> </div> </div> </div> </footer> <script src="js/libs/jquery.min.js"></script>  <script src="css/bootstrap/js/bootstrap.min.js"></script>  <script src="js/libs/metisMenu.min.js"></script>  <script src="js/libs/sb-admin-2.js"></script> <script type="text/javascript"> /* var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-#######-#']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); */ </script> </body> </html>

here is the image I tried to upload
![36ad17bc780bc89f3b6ea40115d9b6c9_13](https://cloud.githubusercontent.com/assets/1186782/8336701/2d22244e-1a5b-11e5-9adf-20f86c497d2a.png)

**Comment by ottonomy** [comment] 2015-06-24 17:51
@sleslie: I saved this image from the upload and tried to extract the assertion from it using Mozilla's Bakery tool (https://github.com/mozilla/openbadges-bakery) -- that yielded an error, which suggests that the assertion isn't baked into the badge properly. It's _possible_ that GitHub did some kind of conversion on it when you uploaded it and stripped out the badges metadata, but it's more likely that this is the cause of the error on Badgr, and we're just delivering you a TERRIBLE error message. I'll build a test case for this and try to serve you a better error in the future at least.

Can you tell me more about where you got this badge, and where you downloaded it?

**Comment by sleslie** [comment] 2015-06-24 17:53
made by me in credly. saved simply by right-clicking, "save image as..." which might be the problem, credly offers no "export" function I could see.

**Comment by ottonomy** [comment] 2015-06-24 17:59
Ah yeah -- I think that's it. The image Credly is showing you isn't the "baked" version; it's just the badgeclass image that applies to all earners. Through Credly, you should be able to export to the Mozilla backpack, then save the image from there, which will be baked in the sending-to-backpack process. We're reaching out to platforms like Credly to see if we can build smoother integration methods for users who want to share their badges from Badgr.

**Comment by sleslie** [comment] 2015-06-24 18:23
gotcha. comically, I did the above process yesterday. I actually went to get the badge from mozilla backpack today and...white screen of death, no matter how many different browsers I tried. Mozilla, I love you but you're bringing me down :-(

**Comment by ottonomy** [comment] 2015-06-29 20:12
Yeah, Mozilla backpack was down for almost a whole day last week. Killer downtime! They're committed to improving it, but problems remain for the short term (and ... we'll see!).

**Closed** 2015-07-01 01:53 UTC
