### ISSUE TITLE
Failed at the node-sass@1.2.3

### ISSUE THREAD

**Issue by shaidar** [concentricsky/badgr-server#4] opened 2015-06-04 19:22 UTC
When running 'npm install' on Mac 10.10.3 in virtualenv get the following error:
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adm/Documents/code/npm-debug.log

**Comment by ottonomy** [comment] 2015-06-04 19:48
Thanks for reporting this bug. We haven't experienced this problem internally, on a variety of environments, including virtualenv on OS X 10.10.3 myself. I will investigate, and we hope to have a satisfying answer for you soon.

**Comment by ottonomy** [comment] 2015-06-08 12:55
@shaidar -- I can't reproduce this on my local machine, but could you test to see if you still get this error if you change the line in package.json from `"gulp-sass": "~1.2.4"` to the latest `"gulp-sass": "~2.0.1"`? It seems a number of people have gotten this error with disparate versions of node-sass, which is a dependency of gulp-sass, and most advice on what version currently works for them is outdated.

**Comment by shaidar** [comment] 2015-06-09 00:08
Yep that was it! Thanks!

**Comment by ottonomy** [comment] 2015-06-09 04:51
Ok. I'll test this modification and release it with the next push, due out very soon. Leaving this issue open fir the moment.

**Comment by ottonomy** [comment] 2015-06-24 04:42
Fixed in 1c3e4e84e5. It seems this bug has appeared in many projects that use this module over time and only occurs intermittently, so hopefully it doesn't recur with a future version of gulp-sass.

**Closed by ottonomy** 2015-06-24 04:42 UTC
