### ISSUE TITLE
can't edit issuer once created

### ISSUE THREAD

**Issue by sleslie** [concentricsky/badgr-server#7] opened 2015-06-24 18:13 UTC
I created an issuer. There is no obvious way to edit it once I did. I needed to edit it because it had the wrong logo. It had the wrong logo because the first one I chose was incorrect, but there was no way to not use it and choose a second one (I tried, it didn't replace it.) I thought saving it and then editing it would be the solution, but alas, no obvious way to edit. So maybe 2 separate issues?

**Comment by ottonomy** [comment] 2015-06-24 18:40
@sleslie Thanks for submitting. This is absolutely on the near-term roadmap (this week if I can get to it!). Feel free to create a second issuer with the right logo

I'll investigate why choosing a second logo didn't replace the first one in your view. I have not encountered this bug in my testing. I'll let you know if I can't reproduce it.

My steps will be:
* Fill out Issuer form with name, description, contact email, url
* Add a invalid image (you're right it doesn't accept JPGs though that is undocumented)
* try to save, encounter image error message
* Try to replace with the correct image
* Try to save again

**Comment by dajbelshaw** [comment] 2015-07-14 10:05
Hi @ottonomy is that roadmap public? I'm putting together some options for a client and knowing where you're headed with Badgr (which is already looking great!) would be useful. :)

**Comment by ottonomy** [comment] 2017-04-28 00:25
On https://badgr.io the issuers may now be edited. We will roll out this change to the open source version on next release.

**Comment by lidijarad** [comment] 2017-08-11 13:34
Hi @ottonomy, 

I was wondering if you have an ETA for when the new open source version will be rolled out?

**Comment by ottonomy** [comment] 2018-04-12 18:16
This has been fixed with yesterday's release. The PUT endpoint is now available via /v1 and /v2

**Closed by ottonomy** 2018-04-12 18:16 UTC
Labels: In-development
